# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attend', '0002_auto_20160125_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='commet',
            new_name='comment',
        ),
    ]
