# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleKey', models.IntegerField()),
                ('roleName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userrole',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
